### ISSUE TITLE
Can you help to store the data in the frontmatter of the current week note(eg 2024-W48)? Thanks!

### ISSUE THREAD

**Issue by nanjingman** [GitGorman/weekly-goal-tracker#1]
Can you help to store the data in the frontmatter of the current week note(eg 2024-W48)? Thanks!

**Comment by GitGorman** [comment]
Of course! Can I just check, are you using the periodic notes plugin by Liam Cain?

**Comment by GitGorman** [comment]
I have added compatability with the Periodic Notes plugin in version 1.2.0. Let me know if it works for you and if you have any more suggestions please let me know :). I will close this issue once you let me know that it works.

**Comment by nanjingman** [comment]
It works so well! Thank U very much!
![image](https://github.com/user-attachments/assets/a564aa8a-647b-44d1-8f9a-ff62e0bf72b9)

**Comment by GitGorman** [comment]
Happy to hear :) Reminder you can change the colours in the settings tab if you would like.
